 # file: .travis.yml
language: objective-c

branches:
 only:
 - master
 
xcode_project: TestProject.xcodeproj
xcode_scheme: TestProject
osx_image: xcode6.4
xcode_sdk: iphonesimulator8.4 

script:
  - xctool -workspace TesProject/TestProject.xcworkspace -scheme TestProject -sdk iphonesimulator
  - xctool test -workspace TesProject/TestProject.xcworkspace -scheme TestProjectTests -sdk iphonesimulator
  
before_install:
  - sudo gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi