 # file: .travis.yml
language: objective-c

branches:
 only:
 - master
 
xcode_project: CIProject.xcodeproj
xcode_scheme: CIProject
osx_image: xcode6.4
xcode_sdk: iphonesimulator8.4 

script:
  - xctool -workspace CIProject.xcworkspace -scheme CIProject -sdk iphonesimulator
  - xctool test -workspace CIProject.xcworkspace -scheme CIProjectTests -sdk iphonesimulator
  
before_install:
  #- sudo gem install cocoapods
  - sudo gem install cocoapods --pre
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi